version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore"
    labels: []
  - package-ecosystem: pip
    directory: /scripts
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore"
    labels: []
